import type { Metadata } from "next";
import { Breadcrumb } from "@/components/Breadcrumb";
import { pageMetadata } from "@/lib/metadata";
import { site } from "@/lib/site";

export const metadata: Metadata = pageMetadata({
  title: "Privacy Policy — ISTRIADE GROUP LLC",
  description: "Privacy Policy for the ISTRIADE GROUP LLC corporate website and corporate communications.",
  path: "/privacy/",
});

export default function PrivacyPage() {
  return <section className="legal-page"><div className="container legal-container"><Breadcrumb label="Privacy" /><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p className="legal-updated">Last updated: September 5, 2026</p>
    <h2>1. Scope</h2><p>This Privacy Policy explains how ISTRIADE GROUP LLC ("ISTRIADE," "we," "us," or "our") handles personal information in connection with:</p><ul><li>istriadegroup.com;</li><li>direct corporate enquiries and email communications; and</li><li>other corporate interactions that expressly link to this Privacy Policy.</li></ul><p>Individual ISTRIADE products or services may provide additional or product-specific privacy notices.</p><p>Third-party websites and services linked from this website operate under their own privacy practices.</p>
    <h2>2. Who We Are</h2><p><strong>{site.legalName}</strong> is a technology company based in {site.location}. Corporate website: istriadegroup.com. Contact: <a href={`mailto:${site.email}`}>{site.email}</a>.</p>
    <h2>3. Information We May Collect</h2><h3>Information you provide</h3><p>When you contact ISTRIADE directly, we may receive information such as your name, email address, company or organization, role or job title, the content of your enquiry, information or files you choose to provide, and related business correspondence.</p><p>Please do not send passwords, private authentication keys, full payment-card information or unrelated sensitive personal information through ordinary email.</p><h3>Technical information</h3><p>Our hosting, security and infrastructure providers may process limited technical information necessary to operate and protect the website, such as IP address, browser and device information, requested pages, timestamps, referring information, server or security logs, and similar technical information.</p>
    <h2>4. Corporate Website Functionality</h2><p>The corporate website is primarily informational. In its initial version, it is not intended to provide user accounts, authentication, product checkout, payment processing, customer dashboards or a corporate contact-form database.</p><p>Product-specific functionality is managed separately by the relevant product or service environment.</p>
    <h2>5. How We Use Information</h2><p>We may use personal information to respond to enquiries; communicate about ISTRIADE, its products or services; evaluate potential business relationships or partnerships; route product-specific questions appropriately; maintain business correspondence and records; operate, protect and troubleshoot the website; prevent abuse or security incidents; comply with legal, regulatory, accounting or contractual requirements; and establish, exercise or defend legal rights.</p>
    <h2>6. Service Providers</h2><p>ISTRIADE may use service providers that support website hosting and infrastructure, DNS, content delivery and security, email and communications, file or document storage, business productivity, and professional or technical support.</p><p>These providers may process information as necessary to provide their services and are subject to their own contractual and legal obligations.</p>
    <h2>7. Cookies and Analytics</h2><p>The initial corporate website is intended to operate without non-essential advertising trackers or behavioral advertising technologies.</p><p>Essential technologies may still be used where necessary for website operation, security or infrastructure.</p><p>If ISTRIADE later introduces non-essential analytics, advertising technologies or other technologies that materially change these practices, this Privacy Policy and any required consent mechanisms will be updated accordingly.</p>
    <h2>8. Artificial Intelligence and Automation</h2><p>ISTRIADE may use AI-assisted or automated tools in internal business workflows where appropriate.</p><p>We seek to limit personal information processed through such tools to what is reasonably necessary for the relevant business purpose and to apply appropriate operational controls. AI-assisted outputs are not treated as automatically correct.</p>
    <h2>9. Data Retention</h2><p>We retain personal information for as long as reasonably necessary for the purpose for which it was collected, including business communications, legitimate operational needs, legal obligations, dispute resolution and record keeping. Retention periods may vary according to the nature of the information and the relationship involved.</p>
    <h2>10. International Processing</h2><p>ISTRIADE is based in the United States and operates digitally. Information may therefore be processed in the United States or in other countries where our service providers operate. Where applicable law requires specific safeguards for international data transfers, we will apply appropriate measures to the extent required.</p>
    <h2>11. Your Rights</h2><p>Depending on where you live and the applicable law, you may have rights concerning your personal information, which can include rights to request access, correction, deletion or other restrictions on processing.</p><p>To make a privacy-related request, contact <a href={`mailto:${site.email}`}>{site.email}</a>. We may need to verify your identity before completing certain requests.</p>
    <h2>12. Security</h2><p>ISTRIADE uses reasonable technical and organizational measures intended to protect information against unauthorized access, loss, misuse or alteration. No electronic system or transmission method can be guaranteed to be completely secure.</p>
    <h2>13. Children's Privacy</h2><p>This corporate website is intended for business and general informational use and is not directed to children. ISTRIADE does not knowingly use the corporate website to solicit personal information from children.</p>
    <h2>14. Third-Party Websites</h2><p>This website may link to ISTRIADE products or other third-party websites. Those websites may have separate terms and privacy practices. ISTRIADE's corporate Privacy Policy does not replace a product-specific or third-party privacy notice.</p>
    <h2>15. Changes to This Policy</h2><p>ISTRIADE may update this Privacy Policy when its website, business practices or legal obligations change. The current version will be published on this page with the applicable "Last updated" date.</p>
    <h2>16. Contact</h2><p>Questions about this Privacy Policy may be sent to:<br /><strong>{site.legalName}</strong><br />{site.location}<br /><a href={`mailto:${site.email}`}>{site.email}</a></p>
  </div></section>;
}
