import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumb } from "@/components/Breadcrumb";
import { pageMetadata } from "@/lib/metadata";
import { site } from "@/lib/site";

export const metadata: Metadata = pageMetadata({
  title: "Website Terms — ISTRIADE GROUP LLC",
  description: "Website Terms governing access to and use of the ISTRIADE GROUP LLC corporate website.",
  path: "/terms/",
});

export default function TermsPage() {
  return <section className="legal-page"><div className="container legal-container"><Breadcrumb label="Website Terms" /><p className="eyebrow">Legal</p><h1>Website Terms</h1><p className="legal-updated">Last updated: September 5, 2026</p>
    <h2>1. Operator</h2><p>This website is operated by <strong>ISTRIADE GROUP LLC</strong>, a Wyoming limited liability company ("ISTRIADE," "we," "us," or "our").</p><p>By accessing or using istriadegroup.com, you agree to these Website Terms. If you do not agree, you should not use the website.</p>
    <h2>2. Corporate Website</h2><p>istriadegroup.com is ISTRIADE&apos;s corporate website. It provides information about ISTRIADE GROUP LLC, its products and systems, its capabilities, its operating approach, and methods of contacting the company.</p><p>The corporate website is not intended to serve as the complete commercial terms, pricing source or contractual documentation for every ISTRIADE product.</p>
    <h2>3. Product-Specific and Commercial Terms</h2><p>Individual ISTRIADE products and services may have their own terms of service, service descriptions, pricing, payment terms, refund or cancellation policies, privacy notices, access conditions or other contractual documentation.</p><p>Where product-specific terms apply, they are provided through the relevant product website, checkout, order process, onboarding flow or written agreement. These Website Terms do not replace those product-specific terms.</p><p>For purchases made directly from ISTRIADE where no more specific commercial terms apply, the general <Link href="/commercial-policies/">Commercial Policies</Link> explain payment, fulfillment, refund, cancellation and customer-support practices.</p>
    <h2>4. Informational Content</h2><p>ISTRIADE seeks to keep corporate website information accurate and current. However, product information may evolve, external links may change, content may be updated without prior notice, and general corporate information should not be interpreted as a contractual commitment concerning a specific product or service unless expressly stated otherwise.</p>
    <h2>5. No Professional Advice</h2><p>Unless expressly stated in a specific engagement, general information on this corporate website does not constitute legal, tax, accounting, financial or other regulated professional advice. Users should obtain appropriate professional advice where necessary.</p>
    <h2>6. Intellectual Property</h2><p>Unless otherwise stated, the website and its original content, branding, visual systems, text, graphics, designs, software and other materials are owned by or licensed to ISTRIADE GROUP LLC and are protected by applicable intellectual-property laws.</p><p>You may access and use the website for lawful personal or business informational purposes. You may not reproduce, sell, misrepresent, remove attribution from, or commercially exploit protected ISTRIADE materials without appropriate authorization.</p>
    <h2>7. Acceptable Use</h2><p>You may not use this website to violate applicable law; interfere with website security or operation; attempt unauthorized access to systems or data; distribute malware or harmful code; conduct abusive automated activity; impersonate ISTRIADE or another person; misrepresent an affiliation with ISTRIADE; or infringe intellectual-property or other rights.</p>
    <h2>8. External Websites</h2><p>The corporate website may link to ISTRIADE product websites, platforms operated by service providers, or other third-party websites. ISTRIADE does not control third-party websites merely because this website links to them. Their own terms, policies and practices apply.</p>
    <h2>9. Website Availability</h2><p>ISTRIADE may modify, suspend, replace or discontinue parts of the corporate website at any time. We do not guarantee that the website will always be uninterrupted, error-free or continuously available.</p>
    <h2>10. Disclaimer</h2><p>To the extent permitted by applicable law, the corporate website is provided on an "as available" basis. ISTRIADE does not guarantee that general website content will be suitable for every purpose or that information obtained through external websites will be accurate or available.</p><p>Nothing in these Website Terms excludes rights or obligations that cannot lawfully be excluded.</p>
    <h2>11. Limitation of Liability</h2><p>To the maximum extent permitted by applicable law, ISTRIADE GROUP LLC will not be liable for indirect, incidental, special or consequential losses arising solely from use of, or inability to access, the general corporate website.</p><p>This limitation does not apply where liability cannot lawfully be limited or excluded. Liability relating to a purchased product or professional service is governed by the applicable product-specific terms, Commercial Policies or agreement.</p>
    <h2>12. Governing Law</h2><p>These Website Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict-of-laws principles, subject to any mandatory rights or laws that cannot legally be waived.</p>
    <h2>13. Changes</h2><p>ISTRIADE may update these Website Terms when the website, company practices or legal requirements change. The current version will be published on this page with the applicable "Last updated" date.</p>
    <h2>14. Contact</h2><p>Questions about these Website Terms may be sent to:<br /><strong>{site.legalName}</strong><br />{site.businessAddressText}<br /><a href={`mailto:${site.supportEmail}`}>{site.supportEmail}</a></p>
  </div></section>;
}
